version: '3'
services:
  ui:
    build: ./ui
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-net
  api:
    build: ./api
    ports:
      - '9500:9500'
    depends_on:
      - mongo
    networks:
      - app-net

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-net

networks:
  app-net:
    