version: '3'
services:
  
  nexus:
    image: sonatype/nexus3
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - "8081:8081"
    networks:
      - App-net
  
volumes:
    nexus-data:

networks:
  App-net:
